apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-cron-job-demo
spec:
  schedule: "0 5 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kube-cron-job-demo
              image: kube-cron-job-demo:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure